import birdCrackers from './bird-crackers.png';
import lakshmi from './Laxmi4 Crackers.png'
import twosound from './twosound.png'
import chakkarspl from './chakkar(spl).png'
import chakkardlx from './chakkar(dlx).png'
import chakkaraso from './chakkarask.png'
import wheel from './wheel.png'
import big from './flowerbig.png'
import special from './flowerspecial.png'
import asoka from './flowerasoka.png'
import cone from './cone.png'
import koti from './koti.png'
import kotidlx from './kotidlx.png'
import hydro from './hydro.png'
import king from './king.png'
import classic from './classic.png'
import bullet from './bullet.png'
import ganga from './ganga.png'
import color from './color.png'
import rocket from './rocket.png'
import two from './two.png'
import three from './three.png'
import rocketbomb from './rocketbomb.png'
import stripped from './stripped.png'
import red from './red.png'
import stone from './stone.png'
import pencil from './pencil.png'
import star from './star.png'
import shot12 from './12shot.png'
import star12 from './12star.png'
import shot from './shot.png'
import triple from './triple.png'
import paper from './paper.jpeg'
import pipe from './pipe.png'
import pipel from './pipeL.png'
import pipem from './pipem.png'
import shot25 from './25shot.png'
import shot30 from './30shot.png'
import shot50 from './50shot.png'
import shot60 from './60shot.png'
import shot100 from './100shot.png'
import shot120 from './120shot.png'
import shot600 from './600shot.png'
import d100 from './100.png'
import candle from './candle.png'
import drone from './drone.png'
import butterfly from './butterfly.png'
import minmax from './minmax.png'
import d24 from './24.png'
import d28 from './28.png'
import g28 from './28g.png'
import gaint56 from './gaint56.png'
import tin from './tin.jpg'
import mid from './midnight.png'
import music from './music.png'
import onehit from './onehit.png'
import g1g2g5g10 from './g1g2g5g10.png'
import ben from './ben.jpg'
import magic from './magic.png'
import chota5 from './chota5.jpg'
import colorbullet from './colorbullet.png'
import peacock from './peacock.png'
import photo from './photo.png'
import single from './single.png'
import cartoon from './cartoon.png'
import redbijili from './redbijili.png'
import bheem from './bheem.png'
import asrafi from './asrafi.jpeg'
import topten from './topten.jpg'
import ranga from './ranga.png'
import siren from './siren.png'
import notimage from './notimage.png'
import electric7cm from './electric7cm.jpeg'
import crackling7cm from './crackling7cm.png'
import green7cm from './green7cm.png'
import red7cm from './red7cm.png'
import electric10cm from './electric10cm.jpg'
import crackling10cm from './crackling10cm.png'
import green10cm from './green10cm.png'
import red10cm from './red10cm.png'
import fiveinone from './fiveinone.png'
import electric12cm from './electric12cm.png'
import crackling12cm from './crackling12cm.png'
import green12cm from './green12cm.jpg'
import red12cm from './red12cm.jpg'
import electric15cm from './electric15cm.png'
import crackling15cm from './crackling15cm.png'
import green15cm from './green15cm.png'
import red15cm from './red15cm.jpeg'
import fiveinone15cm from './fiveinone15cm.jpeg'
import electric30cm from './electric30cm.jpeg'
import crackling30cm from './crackling30cm.jpg'
import green30cm from './green30cm.png'
import red30cm from './red30cm.png'
import electric50cm from './electric50cm.png'
import crackling50cm from './crackling50cm.jpeg'
import redgreen50cm from './redgreen50cm.png'
import umbrella from './umbrella.jpg'


import sparrow from './sparrow.jpg'
import peacock9cm from './peacock9cm.jpg'
import lakshmi9cm from './lakshmi9cm.jpg'
import krishna10cm from './krishna10cm.jpg'
import hitler from './hitler.jpg'
import twosound1 from './twosound.jpg'
import hercules from './hercules.jpg'
import twosoundgaint from './twosoundgaint.jpg'
import stdbijili from './stdbijili.jpg'
import stdredbijili from './stdredbijili.jpg'
import stdgaint from './stdgaint.jpg'
import stdstripped from './stdstripped.jpg'
import stdbullet from './stdbullet.jpg'
import stdhydro from './stdhydro.jpg'
import stdatom from './stdatom.jpg'
import stdsilver from './stdsilver.jpg'
import stdcolour from './stdcolour.jpg'
import stdthunder from './stdthunder.jpg'
import stdsss from './stdsss.jpg'
import stdkargil from './stdkargil.jpg'
import stdboom from './stdboom.jpg'
import stdganga from './stdganga.jpg'
import stdbig from './stdbig.jpg'
import stdspecial from './stdspecial.jpg'
import stdgaint1 from './stdgaint.jpg'
import stddeluxe from './stddeluxe.jpg'
import stdtri from './stdtri.jpg'
import stdsmall from './stdsmall.jpg'
import stdcyn from './stdcyn.jpg'
import stdtrim from './stdtrim.jpg'
import stdfountain from './stdfountain.jpg'
import stdjade from './stdjade.jpg'
import stdcheers from './stdcheers.jpg'
import stdgreat from './stdgreat.jpg'
import stdtower from './stdtower.jpg'
import stdfoun from './stdfoun.jpg'
import stdmoney from './stdmoney.jpg'
import stdsun from './stdsun.jpg'
import stdjewel from './stdjewel.jpg'
import stdhappy from './stdhappy.jpg'
import stdjet from './stdjet.jpg'
import stdpop from './stdpop.jpg'
import stdfog from './stdfog.jpg'
import stdlittle from './stdlittle.jpg'
import stdchakk from './stdchakk.jpg'
import stdaso from './stdaso.jpg'
import stdchakkd from './stdchakkd.jpg'
import stdsplc from './stdsplc.jpg'
import stdchakksu from './stdchakksu.jpg'
import stdrw from './stdrw.jpg'
import stdmega from './stdmega.jpg'
import stdtwin from './stdtwin.jpg'
import stdscary from './stdscary.jpg'
import stdwizz from './stdwizz.jpg'
import stdfour from './stdfour.jpg'
import stdmulti from './stdmulti.jpg'
import stdmagnet from './stdmagnet.jpg'
import stdfire from './stdfire.jpg'
import stdstard from './stdstard.jpg'
import stdsilverstar from './stdsilverstar.jpg'
import stdstar from './stdstar.jpg'
import stdpencil from './stdpencil.jpg'
import stdrocket from './stdrocket.jpg'
import stdrocket1 from './stdrocket1.jpg'
import stdrocket2 from './stdrocket2.jpg'
import stdrocket3 from './stdrocket3.jpg'
import stdrocket4 from './stdrocket4.jpg'
import stdrocket5 from './stdrocket5.jpg'
import stdgift from './stdgift.png'
import stdbobby from './stdbobby.jpg'
import stdbobbyc from './stdbobbyc.jpg'
import stdcolour12 from './stdcolour12.jpg'
import stdred12 from './stdred12.jpg'
import stdgold30 from './stdgold30.jpg'
import stdlemon15 from './stdlemon15.jpg'
import stdcrack15 from './stdcrack15.jpg'
import stdcrack30 from './stdcrack30.jpg'
import stdlav15 from './stdlav15.jpg'
import stdgold15 from './stdgold15.jpg'
import stdmagictree from './stdmagictree.jpg'
import stdrom from './stdrom.jpg'
import stdseven from './stdseven.jpg'
import stdaer from './stdaer.jpg'
import stdmet from './stdmet.jpg'
import stdshot from './stdshot.jpg'
import stdrush from './stdrush.jpg'
import stdswa from './stdswa.jpg'
import stdgold from './stdgold.jpg'
import stdchange from './stdchange.jpg'
import stdmine from './stdmine.jpg'
import stdfat from './stdfat.jpg'
import stdrain from './stdrain.jpg'
import stdyah from './stdyah.jpg'
import stdchat from './stdchat.jpg'
import stdwise from './stdwise.jpg'
import stdsnow from './stdsnow.jpg'
import stdhappy1 from './stdhappy.jpg'
import stdcluster from './stdcluster.jpg'
import stdwand from './stdwand.jpg'
import stdcandy from './stdcandy.jpg'
import stdfive from './stdfive.jpg'
import stddiamond from './stddiamond.jpg'
import stdjil from './stdjil.jpg'
import stdmatrix from './stdmatrix.jpg'
import stdlaser from './stdlaser.jpg'
import stdcuk from './stdcuk.jpg'
import stdpoker from './stdpoker.jpg'
import stddollar from './stddollar.jpg'
import stdjack from './stdjack.jpg'
import stdtug from './stdtug.jpg'
import stdcart from './stdcart.jpg'
import stdtreasure from './stdtreasure.jpg'
import stdrang from './stdrang.jpg'
import stdfrog from './stdfrog.jpg'
import stdstone from './stdstone.jpg'
import stddisco from './stddisco.jpg'
import stdwhip from './stdwhip.jpg'
import stdtv from './stdtv.jpg'
import stdparty from './stdparty.jpg'
import stdrose from './stdrose.jpg'
import stdgrape from './stdgrape.jpg'
import stdcolormagic from './stdcolormagic.jpg'
import stdval from './stdval.jpg'
import stdspraym from './stdspraym.jpg'
import stdspray from './stdspray.jpg'
import stdcon from './stdcon.jpg'
import stdlittle1 from './stdlittle.jpg'
import stdv from './stdv.jpg'
import stdtorch from './stdtorch.jpg'
import stdfogc from './stdfogc.jpg'
import stdfog1 from './stdfog.jpg'
import std80 from './std80.jpg'
import std120 from './std120.jpg'
import std500 from './std500.jpg'
import std250 from './std250.jpg'
import std200 from './std200.jpg'
import std125 from './std125.jpg'
import std100 from './std100.jpg'
import stde from './stde.jpg'
import stdthunder1 from './stdthunder.jpg'
import std1000 from './std1000.png'
import std56 from './std56.png'
import std1001 from './std1001.png'
import std2000 from './std2000.png'
import std5000 from './std5000.png'
import std10000 from './std10000.png'
import stdcap from './stdcap.jpg'
import stdbirth from './stdbirth.jpg'
import stdballoon from './stdballoon.jpg'
import stdstarfire from './stdstarfire.jpg'
import stdpan from './stdpan.jpg'
import stdavenger from './stdavenger.jpg'
import stdpo from './stdpo.jpg'
import stdbrand from './stdbrand.png'
import stdturn from './stdturn.jpg'
import stdwonder from './stdwonder.jpg'
import stdparr from './stdparr.jpg'
import stdsing from './stdsing.jpg'
import std240 from './std240.jpg'
import std60 from './std60.jpg'
import std40 from './std40.jpg'
import std30 from './std30.jpg'
import std25 from './std25.jpg'
import std20 from './std20.jpg'
import std12 from './std12.jpg'




export const assets = {

  sparrow,peacock9cm,lakshmi9cm,krishna10cm,hitler,twosound1,
  stdbobby,stdbobbyc,stdcolour12,stdred12,stdgold30,stdlemon15,stdcrack15,stdcrack30,stdlav15,
  stdgold15,stdcap,stdbirth,stdballoon,
  stdturn,stdwonder,stdparr,stdsing,
  std240,std60,std40,std30,std25,std20,std12,
  stdstarfire,stdpan,stdavenger,stdpo,stdbrand,
  std1000,std56,std1001,std2000,std5000,std10000,
  std80,std120,std500,std250,std200,std125,std100,stde,stdthunder1,
  stdparty,stdrose,stdgrape,stdcolormagic,stdval,stdspraym,
  stdspray,stdcon,stdlittle1,stdv,stdtorch,
  stdfogc,stdfog1,
  stdwand,stdcandy,stdfive,stddiamond,stdjil,stdmatrix,stdlaser,stdcuk,stdpoker,stddollar,stdjack,
  stdtug,stdcart,stdtreasure,stdrang,stdfrog,stdstone,stddisco,stdwhip,stdtv,
  stdmagictree,stdrom,stdseven,stdaer,stdmet,stdshot,stdrush,stdswa,stdgold,
  stdchange,stdmine,stdfat,stdrain,stdyah,stdchat,stdwise,stdsnow,stdhappy1,stdcluster,
  hercules,twosoundgaint,stdbijili,stdredbijili,stdgaint,stdstripped,
  stdbullet,stdhydro,stdatom,stdsilver,stdcolour,stdthunder,
  stdsss,stdkargil,stdboom,stdganga,stdgift,
  stdfour,stdmulti,stdmagnet,stdfire,stdstard,stdsilverstar,stdstar,
  stdbig,stdspecial,stdgaint1,stddeluxe,stdtri,stdsmall,
  stdcyn,stdtrim,stdfountain,stdjade,stdcheers,stdgreat,
  stdtower,stdfoun,stdmoney,stdsun,stdjewel,stdhappy
  ,stdjet,stdpop,stdfog,stdlittle,stdchakk,stdaso,stdchakkd,
  stdsplc,stdchakksu,stdrw,stdmega,stdtwin,stdscary,stdwizz,stdpencil,
  stdrocket,stdrocket1,stdrocket2,stdrocket3,stdrocket4,stdrocket5,



  birdCrackers, stripped, red, stone, pencil, star, shot, shot12, star12,
  triple, paper, pipe, pipel, pipem, shot25, d100, candle, drone, butterfly,
  minmax, d24, d28, g28, gaint56, tin, mid, music, onehit, topten, ranga, siren,
  shot30, shot50, shot60, shot100, shot120, shot600, g1g2g5g10, asrafi,
  ben, magic, chota5, colorbullet, peacock, photo, single, cartoon, redbijili, bheem,
  lakshmi, notimage,electric7cm,electric10cm,electric12cm,crackling10cm,crackling12cm,crackling7cm,
  green10cm,green12cm,green7cm,red10cm,red12cm,red7cm,fiveinone,
  twosound,electric15cm,electric30cm,electric50cm,
  crackling15cm,crackling30cm,crackling50cm,red15cm,red30cm,green15cm,green30cm,redgreen50cm,
  fiveinone15cm,umbrella,
  chakkardlx,
  chakkarspl,
  chakkaraso,
  wheel,
  big,
  special,
  asoka,
  cone, koti, kotidlx, hydro, king, classic, bullet, ganga, color, rocket, two, three, rocketbomb,
};
